CREATE DATABASE BD_GINCANA_SABER;
USE BD_GINCANA_SABER;

CREATE TABLE AUTORES(
	ID_AUTOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    NACIONALIDADE VARCHAR(100)
);

CREATE TABLE LIVROS(
	ID_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    ID_AUTOR INT,
    ANO_PUBLICACAO DATE,
    PRECO DECIMAL(10,2),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID_AUTOR)
);

CREATE TABLE VENDAS(
	ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_LIVRO INT,
    DATA_VENDA DATE,
    QUANTIDADE INT,
    VALOR_TOTAL INT
);